version: "3"

volumes:
  {{ your_project_name }}_local_postgres_data: {}
  {{ your_project_name }}_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ your_project_name }}_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./../{{ your_project_name }}:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ your_project_name }}_production_postgres
    volumes:
      - {{ your_project_name }}_local_postgres_data:/var/lib/postgresql/data
      - {{ your_project_name }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6

  ceelry:
    <<: *django
    image: {{ your_project_name }}_local_celery
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
