version: "3"

volumes:
  {{ your_project_name }}_local_postgres_data: {}
  {{ your_project_name }}_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ..
      dockerfile: ./bin/compose/local/django/Dockerfile
    image: {{ your_project_name }}_local_django
    depends_on:
      - postgres
    volumes:
      - ./{{ your_project_name }}:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "20002:8000"
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: ./bin/compose/production/postgres/Dockerfile
    image: {{ your_project_name }}_local_postgres
    volumes:
      - {{ your_project_name }}_local_postgres_data:/var/lib/postgresql/data
      - {{ your_project_name }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "20003:5432"
