version: "3"

volumes:
  _local_postgres_data: {}
  _local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: _local_django
    container_name: _local_django
    depends_on:
      - postgres
    volumes:
      - ./..:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: _production_postgres
    container_name: _local_postgres
    volumes:
      - _local_postgres_data:/var/lib/postgresql/data
      - _local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
