version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: template_for_analyze_production_django
    volumes:
      - production_django_media:/app/template_for_analyze/media
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: template_for_analyze_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: template_for_analyze_production_celeryworker
    command: /start-celeryworker

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: template_for_analyze_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
