version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: ..
      dockerfile: ./bin/compose/production/django/Dockerfile
    image: {{ your_project_name }}_production_django
    volumes:
      - production_django_media:/app/{{ your_project_name }}/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./bin/.envs/.production/.django
      - ./bin/.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: ./bin/compose/production/postgres/Dockerfile
    image: {{ your_project_name }}_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./bin/.envs/.production/.postgres

  nginx:
    build:
      context: ..
      dockerfile: ./bin/compose/production/nginx/Dockerfile
    image: {{ your_project_name }}_local_nginx
    ports:
      - "8402:80"
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro

  redis:
    image: redis:6

  celery:
    <<: *django
    image: {{ your_project_name }}_production_celery
    command: /start-celeryworker
